### ISSUE TITLE
Saving the Video to the app storage

### ISSUE THREAD

**Issue by HarshitSingh1509** [AbedElazizShe/light_compressor#44]
While compressing the video, the file is saved in app storage, I need to delete that, as in my app, user is compressing many videos of large size, I think this library is storing two videos, one that is original and other is the compressed one. These video are stored in apps storage, so user can't even see or delete it later.
Please is there any way I can solve that.
Thankyou

**Comment by AbedElazizShe** [comment]
Hi @HarshitSingh1509 , thank you for opening this issue. I believe the issue is resolved. I will release a new version soon.

**Comment by HuynhThien82** [comment]
Hi @AbedElazizShe , thank you for your hard work. But, I think the issue is still there on Android. Could you please check it?
![CleanShot 2024-06-09 at 23 15 59@2x](https://github.com/AbedElazizShe/light_compressor/assets/14513693/39a1d185-a972-44ab-9dea-42c0de4ca98c)
